### ISSUE TITLE
Build Task "Power Platform Import Solution": New setting "Activate Plugin" suddenly available and unchecked per default

### ISSUE THREAD

**Issue by zimflo** [microsoft/powerplatform-build-tools#131]
Hi,

the following setting has been added recently. I couldn´t find a proper announcement in the release notes. I´ve only recognized it after the deployment when all the plugin steps were inactive. So the way it is handled at the moment is a bit unfortunate.

Furthermore, the old setting "Activate processes (workflows) after import" seems to be redunant now.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/81113728/176915212-5f4cf83d-5ead-4bb6-8095-b95a528cd83c.png">

Thanks!

**Comment by daryllabar** [comment]
@zimflo of you're needing to renable all your plugins, this may help https://dotnetdust.blogspot.com/2022/07/enabling-or-disabling-all-plugin-steps.html?m=1

Also I'm assuming it's fairly obvious from a continuity perspective, that plugins should be enabled by default

**Comment by daryllabar** [comment]
This is a breaking change for anyone that is not specifying a version number run the yaml as well.  Prior to this, plugins we're always enabled by default.  Now running the pipeline will disable all plugin steps.  A very very very major issue for people that depend on plugins for data integrity or security

**Comment by davidjenni** [comment]
@zimflo @daryllabar issue is understood:
The older PP-BT's task input "PublishWorkflows" was setting what the Dataverse ServiceClient's .ImportSolutionAsync() calls activatePlugins. When we transposed from the Powershell to the TS/pac CLI implementation, we mistakenly *added* a new input, instead of sticking with the old name.
IIRC, the "publishWorkflow" stems from what the older CrmServiceClient used to call in its ImportSolutionRequest, but it had the same semantic intention: activate plugins

Here's the fix proposal: 
- To not add an unnecessary breaking change, we will mark the "Activate Workflows (aka. PublishWorkflows)" as deprecated in the ImportSolution's input param definition and point to the new input param "Activate Plugin" since it also correctly reflects the actual semantics
- the "Activate Plugin" will be updated to have this param true/on by default
- the task's internal logic will query both the old and new name, and if either is true, it will result in activatePlugin=true to be sent along w/ the import request
- minor: we'll change the ordering in the GUI to have the now-deprecated Activate Process show last

**Comment by davidjenni** [comment]
@zimflo @daryllabar @vladnega
Our fixes to pac CLI and the import solution tasks have been merged. We're now kicking off our official build for an updated v >= 1.0.83 that has the fixes. ETA ~3:30 PDT today

Rel notes:
- 'Import Solution' task:
  - 'ActivatePlugins' task parameter is on by default; deprecate param 'PublishWorkflows' but consider both for plugin activation (#131)
  - fix forced 'PublishChanges' and its potential http timeout on PublishAllCustomizations (#129)
  - introduces a new "PublishCustomizationChanges" task parameter to also publish customizations after successful import

**Comment by davidjenni** [comment]
Fix has been deployed to VS Marketplace as 1.0,84

**Comment by davidjenni** [comment]
@zimflo @daryllabar @vladnega
Right now, we've rolled back to the PS based implementation 1.0.85 (see #144).
The issue has been addressed in both pac CLI and the pp-bt TS layer, fixed and verified, changes have been backported to main.
Resolving
