### ISSUE TITLE
The Power Platform Build Tools are not backwards compatible

### ISSUE THREAD

**Issue by bermo** [microsoft/powerplatform-build-tools#136]
It seems impossible to point to an older version of the Power Platform Build Tools or I am missing something!

The latest version (1.0.82) has broken our pipelines, and we have an end of financial year release that is failing.  We simply want to use the previous stable version of the task (1.0.77) that was successfully tested everything against, but how is this done - is it even possible?

![image](https://user-images.githubusercontent.com/8371455/176963256-336bdc11-92af-458c-acf5-97b4d9a83048.png)

I read the following in regards to versioning in another issue which has been raised recently, but it doesn't seem to be true or not documented properly:

> RE: versioning: It was a conscious choice by the team, as it has the least amount of pain on existing customers. Since both the old PS based and the pac CLI based versions do depend on having an initial ToolInstaller, there is no mix and match between e.g. @0 ToolInstaller and a @1 DeployPackage task.

We had similar issues with this task for the 1.0.76 release which was fixed by 1.0.77 on the same day but still caused issues for us.

**Comment by davidjenni** [comment]
@bermo as you remarked, there is no pinning back, sorry. What are the concrete issues you're encountering? We're about 1 hr away from publishing fixes for #129 and #131

**Comment by bermo** [comment]
Thanks for the prompt response - the latest update seems to have fixed the issue.  However, this is the 2nd time in a few weeks we've had an issue where we've needed to wait for the task/s to be updated.  Is is possible to include pinning in the next versions if there are more regressions in future releases?

**Comment by davidjenni** [comment]
@bermo thanks for confirming the fixes in #129 and #131. I'll close this one since it is in essence a duplicate.

RE: pinning: The only selection that AzDevOps tasks can expose to pipeline author (i.e. pinning) is via the "Task version" field your screenshot above has.
But given the interdependency between e.g. the ImportSolution to a previous ToolInstaller task, those version must all match, otherwise either the PS modules, or for the latest build, the pac CLI runtime would be missing.
And in the AzDevOps task deployment model, the latest version, e.g. "1.0.84" wins over a previous "1.0.83" version. This creates that high backwards compatibility hurdle we've been battling with over the past days
