### ISSUE TITLE
Power Platform checker fails with new Build Task update

### ISSUE THREAD

**Issue by lar-mar** [microsoft/powerplatform-build-tools#140]
Hello,

since the update for the BuildTasks we are facing an issue with Power Platform Checker.
It suddenly stopped working:
![image](https://user-images.githubusercontent.com/15412588/177134260-b69fbcdd-32d6-4084-a068-fe9dcfc4a721.png)

The task configuration wasn't changed and does not use custom endpoint although the error message states so.
![image](https://user-images.githubusercontent.com/15412588/177134524-d73ccc5f-9b4b-4b3a-8154-64de2cee8ce9.png)

**Comment by davidjenni** [comment]
@lar-mar This is ultimately a typo/finger twister:
![image](https://user-images.githubusercontent.com/3200210/177665947-123fb2d2-49a4-4829-8fd3-be30b0ac172b.png)
typo: `httts` instead of `https`

To remain backwards compatible with the PS implementation, the checker task tries to determine which checker endpoint to use based on the region part of the environment url (e.g. crm, crm4, crm9 etc.). That envUrl can come either via the BuildTools.EnvironmentUrl pipeline variable but also as fallback, from the "server Url" property of the service connection.

We've since also rolled back to the PS-based PP-BT implementation, which was/is more tolerant to a pot. invalid url; see #144
