### ISSUE TITLE
Importing a solution fails if the version number is the same

### ISSUE THREAD

**Issue by MattTrinder1** [microsoft/powerplatform-build-tools#212]
As the title - attempting to import a managed solution when the version is already installed causes the task to fail with an error.  We need an "Skip if the same version" option on the import solution task.

**Comment by davidjenni** [comment]
@MattTrinder1 this is by design of Dataverse: a managed solution is treated as immutable by Dataverse, hence it's not possible to replace a managed solution of the same version number. Your options are to either delete the solution first, or as best practice, ensure the newer solution has a higher version number

**Comment by MattTrinder1** [comment]
@davidjenni  that's not really the point though - we don't want to replace or delete the existing solution, we just want the pipeline to skip the install if the versions are the same, rather than fail with an error.
We could do the version check ourselves, and skip the install on the pipeline side, but the powerplatform-build-tools don't appear to have any way to query a solution version from dataverse.

**Comment by MattB-msft** [comment]
Package deployer, which is available for your use, has this functionality by default.  I would recommend you use it if that is your need

**Comment by MattTrinder1** [comment]
Our existing build pipelines (of which we have dozens) currently produce managed solutions - I really don’t want to have to update all of them to create packages instead. You need to remember that there are thousands of pipelines out there using the WaelHamze tools - if you want people to start using the MS tools by default instead then you need to offer the same feature set and make the process of moving over as seamless as possible; at present you don’t.

**Comment by MattB-msft** [comment]
@MattTrinder1 I am aware of the deep footprint that both Wael's tools and our PowerShell modules have. Wael also has tools available to deploy packages.  Many of the features Wael added are a subsets of the capabilities that Package Deployer provides to allow folks to avoid building a packages, which was until recently a bit of a chore. 

With the current toolset, (pac cli) is extremely easy to create packages. 
To create a package to support this effort, you would do the following. 
1. create new package using pac package init
2. add a reference to the output of your solution build to it using pac package add-solution <path\name> <properties>  ( you can do that for each solution you want to install, but install order matters, so make sure you set the order bit correctly) 
3. compile that with your project and publish it, which will give you a package.zip file you can pass to the package deploy leg. 

That's pretty much it. 

Switching to that process given you the following rules by default: 
Solution Import rules:
if the incoming solution unique name is not found  => Install
if the incoming solution unique name is found and the version number is lower then found => skip
if the incoming solution unique name is found and the version number is the same as found => skip
if the incoming solution unique name is found and the version number is higher then found => install + upgrade. 

Additionally, 
if you configured it, you could also control install / skip / fail rules on dependencies by solution, allow for the system to decide if the solution needs to be skipped or the deployment should be failed ahead of time due to missing dependencies. 

Thats all configuration for solution deployment. 

Beyond that there is data import functions available and the ability for you to write code as part of the deployment operation as required for setup tasks or other fixup type work. 

This feature set is all part of the Package deployment module.   
The standalone deployment module is not intended to have this level of feature as its wired to the direct install flow (which is what PD uses as well after all the decision logic)

**Comment by SteveGreen27** [comment]
> @MattTrinder1 I am aware of the deep footprint that both Wael's tools and our PowerShell modules have. Wael also has tools available to deploy packages. Many of the features Wael added are a subsets of the capabilities that Package Deployer provides to allow folks to avoid building a packages, which was until recently a bit of a chore.
> 
> With the current toolset, (pac cli) is extremely easy to create packages. To create a package to support this effort, you would do the following.
> 
> 1. create new package using pac package init
> 2. add a reference to the output of your solution build to it using pac package add-solution <path\name>   ( you can do that for each solution you want to install, but install order matters, so make sure you set the order bit correctly)
> 3. compile that with your project and publish it, which will give you a package.zip file you can pass to the package deploy leg.
> 
> That's pretty much it.
> 
> Switching to that process given you the following rules by default: Solution Import rules: if the incoming solution unique name is not found => Install if the incoming solution unique name is found and the version number is lower then found => skip if the incoming solution unique name is found and the version number is the same as found => skip if the incoming solution unique name is found and the version number is higher then found => install + upgrade.
> 
> Additionally, if you configured it, you could also control install / skip / fail rules on dependencies by solution, allow for the system to decide if the solution needs to be skipped or the deployment should be failed ahead of time due to missing dependencies.
> 
> Thats all configuration for solution deployment.
> 
> Beyond that there is data import functions available and the ability for you to write code as part of the deployment operation as required for setup tasks or other fixup type work.
> 
> This feature set is all part of the Package deployment module. The standalone deployment module is not intended to have this level of feature as its wired to the direct install flow (which is what PD uses as well after all the decision logic)

That sounds great @MattB-msft but how would we get the current solution version and set it to a higher number using the Power Platform Build Tools as part of a DevOps pipeline? 

It's great that the package deployment module handles lower, equal and higher versions but they still need to be set in the pipeline.

**Comment by MattB-msft** [comment]
@MattTrinder1 can you describe what your trying to do?  
You initially wanted to skip a deployment if the version was the same, as I described PD will do that. 

The versions PD is working with are the versions of the Incoming solutions (by uniquename of solution) as compared to the versions of the deployed solutions in the target environment.

**Comment by MattTrinder1** [comment]
Our current build pipelines (we have lots) build managed solutions, not packages. I don’t want to have to go through and update them all to produce packages. Solution versions can remain the same from one build to the next (as only some solutions from the whole set may have changed). I want to be able to attempt to deploy a solution which may have the same version as the one currently installed and have the pipeline skip it rather than fail with an error.

**Comment by MattTrinder1** [comment]
>> The versions PD is working with are the versions of the Incoming solutions (by uniquename of solution) as compared to the versions of the deployed solutions in the target environment.

I want exactly this functionality in deploy-solution, not just in deploy-package.
