### ISSUE TITLE
Async Import Times out and Sync gives error: There is no active transaction

### ISSUE THREAD

**Issue by rsonnemans** [microsoft/powerplatform-build-tools#220]
Hi,

As of 17th October, we are having problems with the Import of our solutions.
We had it successfully running as a Async Import for a while now.

I tried changing it to a sync import but then we get the following error message: There is no active transaction. After exactly 3 minutes. 

Details: 

- Using the latest version of PPT 2.0.7.
- Wave 2 update was pushed around that date by MS (Could be coincidence) 
- Our main solution is massive and takes around 1.5 hours to import, now it times out after 6 hours and 15 minutes (i've set the maximum wait time very high). 
- We have 2 smaller solutions that takes around 2 minutes these work fine
- It's an import without Publish, we publish in the following step. 

Thanks in advance!

[tasklog_8 (2).log](https://github.com/microsoft/powerplatform-build-tools/files/9831087/tasklog_8.2.log)

**Comment by davidjenni** [comment]
@rsonnemans a synchronous solution import is indeed doomed to fail, since the synch import request gets terminated on the service/datacenter side due to server http idle timeout enforcement. Setting the Import Solution task to asynchronous is the right way.

It is possible that a Dataverse service update is causal here, but it could also be a change within the solution. But even if it is an issue with your solution, it should get rejected with an error message.
The log you attached only shows the end part of the import task's log, before it gets preempted by AzDevOps.

There's more relevant info captured at the beginning of the log; you might have to copy/paste that info from the live AzDevOps log window while the task runs. To try to shine some light here, can you share:
- the organization id (guid) or url of your target environment
- the timestamp when the import started
- the import job id

On this issue tracker, we can only support our PP-BT tasks themselves, if this points to a service side issue, you will have to contact MS support (which will need that data too).

**Comment by rsonnemans** [comment]
Hi,

Yea the synch / async makes sense.
For our test environment we can see the import is started 3 times by our pipeline. All of these times it eventually throws a "The given key was not present in the dictionary." error.

But if we check in our solution history we can see that the first import ran succesfully.
2nd/3th failed due to a "Import already running" error. 
It's weird the pipeline throws an error, but the solution is imported successfully. 

For full log and solution history see image/file below.
All requested info hopefully is in these files. 

I Also created a ticket with MS support.
I Hope I gave sufficient information. 

[tasklog_8 (5).log](https://github.com/microsoft/powerplatform-build-tools/files/9849695/tasklog_8.5.log)
![SolutionHistory](https://user-images.githubusercontent.com/32477660/197472984-1c661e58-c43c-48ff-ba4a-81b99450aecf.PNG)

**Comment by tiemar** [comment]
I have the same problem. I now as the import usually works fine, start the next stept even when an error occurs, but this is not the best option as we now can not see if a real error occurs without digging into the pipeline daily.

**Comment by rsonnemans** [comment]
Any update on this possible? 

I think issue 242 is identical.

**Comment by rsonnemans** [comment]
Issue has been resolved by MS support.
