### ISSUE TITLE
connector automation

### ISSUE THREAD

**Issue by erwinkramer** [microsoft/powerplatform-build-tools#222]
What's the current best-practice regarding automating Power Platform Connectors inside an automated ci/cd pipeline? 

I don't see specific tasks for creating connectors. What i was thinking of, in a ADO pipeline stage:
1. running the `PowerPlatformToolInstaller` task to make sure i can use the `pac` interface.
2. running a custom powershell task and leveraging the `pac auth create` and  `pac connector` commands.

Would this combination work? Are there better options at the moment?

**Comment by davidjenni** [comment]
@erwinkramer there's a cross-team effort under way to add proper solution/Dataverse support to connectors. Part of that effort is already visible in the pac CLI, see the `pac connector` noun you mentioned. All that work is still in early preview (also indicated in the cli help text).
Given the preview nature, we have not yet wrapped this functionality into CI/CD tasks yet, but will ship proper tasks. Since that work is still in preview, I'd advise against using it in a AzDO pipeline just yet.
