### ISSUE TITLE
ALM Release. Can see Managed and Unmanaged. Only allowed to select UnManaged

### ISSUE THREAD

**Issue by rcatbp** [microsoft/powerplatform-build-tools#223]
Subsequent to #216 and the fix of CLI breaking as it generates _managed.
Now fixed I tried CLI in a release but cannot select the managed solution.

(The build pipeline created the artifacts, running deprecated PowerShell, guessing it shouldn't matter)
I also don't understand why I now get the t>,a>,s> folder structure either 
 
![ALM-release-with-new-cli](https://user-images.githubusercontent.com/96841324/198065195-4e68b0a5-280b-41ac-9812-0e1b2489aa37.png)
![ALM-cli-managed-no-ok-lit-up](https://user-images.githubusercontent.com/96841324/198065279-53d3095c-4a9b-48fb-b7ce-8f293b89c24d.png)
![ALM-cli-UNmanaged-ok-lights-up](https://user-images.githubusercontent.com/96841324/198065339-6ca6d9de-5ad6-4638-b4fc-117849bb890f.png)

**Comment by davidjenni** [comment]
@rcatbp as long as the triggering build pipeline uploaded both the managed and unmanaged solution.zip to the artifact store, your release pipeline's file selection dialog should let you select. Also, after the fix we published, whatever file name should be hannded thru to the import solution task. Is that not what you observe? Can you share the log file for the import task?

re: the cryptic paths: this is the Azure DevOps' agent's way to keep paths short and avoid running into MAX_PATH issues

**Comment by rcatbp** [comment]
Hi David,

Thanks for looking, log attached, the run was okay.

As you saw on the screenshot, cannot select 'managed' odd.

Cheers, richard
________________________________

**Comment by davidjenni** [comment]
@rcatbp not being able to select is indeed weird. This dialog and the capability that a selection is copied into the Location field, and thus into the "Solution Input file" text box is all done on the Azure DevOps side, our task extension has no ability to either make it succeed nor fail (none of our code is running in that experience). I don't know if this is a known issue w/ Azure DevOps' classical pipeline editor?
Since we define the solution input file text box as editable, you can easily override and edit the name to fit.
