### ISSUE TITLE
Error with PowerFX dataverse columns

### ISSUE THREAD

**Issue by aburria-ifr** [microsoft/powerplatform-build-tools#232]
I've found that my ALM pattern (export, unpack, pack and import) breaks using PowerFX formulas in dataverse entities.

For my test, I made a solution with a table. I can export, unpack, pack, and import it into another environment. But then, after adding a PowerFX column in the entity, the import fails. On my target environment, in the solution history I get the error: 
80040216: Error while importing Formula fields name crXYZ_powerfx

If I try to manually import the solution, I can do it without a problem, whether managed or unmanaged. So I know nothing is really missing. 

This problem was originally posted on: 
https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Azure-pipeline-error-with-formula-PowerFX-dataverse-column/m-p/1833107

![image](https://user-images.githubusercontent.com/92777085/199539799-39eeca2e-dfc4-41b8-bd70-5a0ee5fd0e06.png)

![image](https://user-images.githubusercontent.com/92777085/199539510-2ef2590f-d81d-4bdf-a18c-555c283a31ae.png)

**Comment by davidjenni** [comment]
@aburria-ifr @cjbadger we've discovered, and now fixed, 2 somewhat independent issues:
- when packaging a locally unpacked solution via `pac solution pack`, or the "Pack Solution' PP-BT tasks, any PowerFX .yaml file was not detected, and consequently missing from the repackaged solution.zip. On import, this would cause the now-correct error message of a missing dependency
- the "given key was not present in the dictionary" was a status code returned from the Dataverse import API that the pac CLI couldn't decode.

Both of these issues have been fixed with the latest October refresh of pac CLI (version >= 1.20.3) and PP-BT (version >= 2.0.10).

Should this still repro with these fixed versions, please open a new issue with log fragments and repro info
