### ISSUE TITLE
Unpack command deletes solution attachments every 2nd run.

### ISSUE THREAD

**Issue by kousikchatterjee** [microsoft/powerplatform-build-tools#274]
I am trying to unpack a solution which contains some solution attachments for email templates, those are getting deleted after every 2nd unpack command.

Please find the detailed steps:
1. Downloaded a solution using pac solution export.
2. Unpacked and commited to repos which is part of one build.
3. Solution attachments for each email templates contains two files, one with the actual name another one without space and special char, extension.
4. Ran the pipeline to download another version of the same solution and unpacked and commited to the repos with allow delete and allow write flag as true.
5. The original file from the solution attachment folder got deleted showing as "there are unnecessary files".
6. Tried to pack the solution to deploy to another env but got failed with dependency error for the same deleted file.
7. Ran the build pipeline again to export and unpacked and this time the solution attachments contains two files as it was there during the first unpack and pack was successfull.
8. And this cycles keeps continuing.

To export, checkin to repos, pack and deploy to another env I need to run the unpack and commit to repos two times.

**Comment by tehcrashxor** [comment]
Tracking internally as AB#3422382

The way SolutionPackager (and the `pac solution pack/unpack` verbs which use it) works with `--allowDelete` works is:
1. grab file list of all files in destination directory
2. unpack contents of solution, keeping track of which files were written
3. compare the list of pre-existing and written files, and delete those which are not in both lists

The bug here was the code handling EmailTemplates and MailMergeTemplates was writing the files without adding them to the list of written files, and thus step 3 didn't see them as files which should be retained.

**Comment by tehcrashxor** [comment]
The latest release (v2.0.27) has an updated PAC and SolutionPackager with the fix to this unpacking issue.
