### ISSUE TITLE
Power Platform CLI doesn't delete files when using pac solution unpack

### ISSUE THREAD

**Issue by rbnswartz** [microsoft/powerplatform-build-tools#448]
When I export and unpack a solution that has had an entity removed from it into a directory that contains a previously extracted solution contents the files for the the contents don't get deleted even though I gave it the --allowDelete flag.

Steps to reproduce:
- Create a solution and add an entity to it
- Export the solution
- Unpack it using `pac solution unpack --zipfile solution.zip --allowDelete --allowWrite --clobber`
- Remove the entity from the solution
- Export the solution again
- Unpack it again using `pac solution unpack --zipfile solution.zip --allowDelete --allowWrite --clobber`

The command output says that it is deleting files

![image](https://github.com/microsoft/powerplatform-build-tools/assets/724704/a979af52-eb15-45b5-bec0-4ecbc0a0b018)

Expected result
The folder for removed entity gets removed from under Entities/

Actual result
The folder still exists for the entity under Entities/ and still contains all the metadata files

Installed Version: 1.25.5+g24fc1f8
OS: Ubuntu 20.04

**Comment by petrochuk** [comment]
Unable to repro with these steps. Are you sure you published your customizations and there is no entity in second solution.zip?

**Comment by rbnswartz** [comment]
Yes it didn't show up on the customizations.xml file. I'm going to try to replicate it again to make sure I'm not crazy

**Comment by petrochuk** [comment]
Unfortunately, PAC CLI code is not open sourced. What Linux version are you using? We usually test on Ubuntu WSL.

**Comment by rbnswartz** [comment]
I'm using Ubuntu 22.04 with .net 7.0.306 and I installed the tool from the nuget package Microsoft.PowerApps.CLI.Tool 
Let me know if there any other details that would be helpful. I also have a recording of the issue occurring if that is helpful for you.

**Comment by petrochuk** [comment]
If you run `pac telemetry status`, it will show you location of log file. Can you attach it or copy relevant block of logs?

**Comment by rbnswartz** [comment]
Here are the logs from my most recent run 
[paclog.txt](https://github.com/microsoft/powerplatform-build-tools/files/12316669/paclog.txt)

**Comment by petrochuk** [comment]
Unable to repro it on latest version. Feel free to reopen if this is still an issue

**Comment by rbnswartz** [comment]
Brilliant! Thank you!

**Comment by parvezghumra** [comment]
Hi @petrochuk @rbnswartz. I've been facing the same issue in the last few days using Power Platform Build Tools (2.0.82) extension for Azure DevOps with PAC CLI version 1.38.3. The solution unpack task was failing to delete files corresponding to objects that were deleted from my solution if the pipeline was run on an 'ubuntu-latest' agent. The files were deleted successfully when I changed my pipeline to run on 'windows-latest'

**Comment by joshsmithxrm** [comment]
Still reproducible in PAC CLI 1.51.1 (December 2024)

  I can confirm this bug is still present in PAC CLI version 1.51.1 on Ubuntu runners (GitHub Actions ubuntu-latest / Ubuntu 24.04).

  Reproduction:
  1. Have a solution with plugin assemblies, plugin packages, and SDK message processing steps
  2. Delete those components from the solution in the environment
  3. Export and unpack with pac solution unpack --allowDelete --allowWrite --packagetype Both

  Observed behavior:
  - PAC CLI outputs: There are 5 unnecessary files and Deleting files...
  - Files are NOT actually deleted on disk
  - git status shows no deletions

  Expected behavior:
  - Files should be deleted (works correctly on Windows with same PAC CLI version)

  Affected components:
  - PluginAssemblies/**/*.dll.data.xml
  - pluginpackages/**/pluginpackage.xml
  - SdkMessageProcessingSteps/*.xml

  Workaround:
  We're now deleting the solution folder before unpack to ensure a clean state:
  rm -rf "$OUTPUT_FOLDER"
  pac solution unpack --zipfile solution.zip --folder "$OUTPUT_FOLDER" --packagetype Both --allowDelete --allowWrite

  With validation to restore from git if unpack fails.
