### ISSUE TITLE
AADSTS7000215: Invalid client secret provided.

### ISSUE THREAD

**Issue by CoreySutton** [microsoft/powerplatform-build-tools#551]
Receiving the following error when importing a solution via Power Apps CLI running in an Azure DevOps Pipeline using an Client ID and Client Secret as an Application User.

```ps1
Processing asynchronous operation... execution time: 00:35:12 and 29.34% complete

Processing asynchronous operation... execution time: 00:35:16 and 29.39% complete

Processing asynchronous operation... execution time: 00:35:20 and 29.45% complete
Microsoft PowerPlatform CLI
Version: 1.27.6+g9f62afb
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: One or more errors occurred.
    One or more errors occurred.
        External Authentication Requested but not configured correctly. 005
            A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'xxx'.
Trace ID: xxx
Correlation ID: xxx
Timestamp: xxx
                A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'xxx'.
Trace ID: xxx
Correlation ID: xxx
Timestamp: xxx


Usage: pac solution import [--path] [--activate-plugins] [--force-overwrite] [--skip-dependency-check] [--import-as-holding] [--publish-changes] [--convert-to-managed] [--async] [--max-async-wait-time] [--settings-file] [--skip-lower-version]

  --path                      Path to solution zip file. If not specified, assumes the current folder is a cdsproj project. (alias: -p)
  --activate-plugins          Activate plug-ins and workflows on the solution. (alias: -ap)
  --force-overwrite           Force an overwrite of unmanaged customizations (alias: -f)
  --skip-dependency-check     Skip dependency check against dependencies flagged as product update (alias: -s)
  --import-as-holding         Import the solution as a holding solution. (alias: -h)
```

This only appears to happen for long-running solution imports, when the solution import takes over an hour. 

I assume this is caused by the [token lifetime](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-continuous-access-evaluation#token-lifetime) configuration. We can [configure token lifetimes ](https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes) however this appears to be a tenant setting rather than per application registration.

1. Is this the correct interpretation of this error message?
2. How should this issue be resolved?

**Comment by tehcrashxor** [comment]
Yep, issue comes from the token lifetime and the differences in the auth stack for SPNs.

For regular users, AAD responds to the login by providing an Access Token (with default 1 hour expiry) and a Refresh Token.  MSAL uses that Refresh Token both for requesting new Access Tokens once the current one expires, and also allows for requests to grab a token for other resources, such as hitting the Admin endpoint for the `pac admin ...` verbs, the Power Apps Checker endpoint for `pac solution check`, or a different org if we're switching to another org with `pac org select`.

SPNs however do not receive a Refresh Token from AAD, so the Access Token will expire after an hour.  In order to request a new Access Token, MSAL needs the SPN's Client Secret, but we do not currently store that information as there was not a good way to persist that value.

I've recently been testing persisting secret securely via value using the MSAL Extension's [Cross Plat Token Cache](https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/token-cache-serialization?tabs=desktop) (under the "Desktop Apps" tab on the docs page) which uses the Windows Data Protection API, Mac KeyChain, or Gnome Key Ring for Linux machines to securely store that value, which may be shipping with a future release.

We should also have better error messaging shortly for that scenario, as the AAD error isn't the most obvious explanation as to what's occurring.
