### ISSUE TITLE
pac paportal and pac powerpages not working for newly created power pages sites

### ISSUE THREAD

**Issue by aka963** [microsoft/powerplatform-build-tools#642]
Hi,

I have followed the steps in the various articles, but I end up with the below message. Please help

Information:
Be careful when you're updating public sites. The changes you make are visible to anyone immediately. To check site visibility go to https://make.powerpages.microsoft.com/.
To get additional information, please visit https://go.microsoft.com/fwlink/?linkid=2204350

Started downloading website _WEBSITEID_
Connected to... _UAT Enivronment_
Connected as _admin_
Microsoft PowerPlatform CLI
**Version: 1.28.3+g4ba7dfd**
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

**Error: Power Pages entities aren't available on this org, please install Power Pages package on the org.**

**Comment by aka963** [comment]
Hi,

Thank you. I figured out that including -mv in the command will download the site.

**Comment by Aryansharmamic** [comment]
> Hi,
> 
> Thank you. I figured out that including -mv in the command will download the site.

Hi can you please tell me exactly where you entered -mv because placing it at end gives me an error

/`Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: bd5ac722-8361-47f8-a595-1593d923ccc2, Exception Type: System.NullReferenceException
The diagnostic logs can be found at: C:\Users\AryanSharma\AppData\Local\Microsoft\PowerAppsCli\Microsoft.PowerApps.CLI.1.30.4\tools\logs\pac-log.txt
`

this log file also don't contain any useful data

**Comment by aka963** [comment]
If your downloading from "Portal Managment" then

pac paportal download --path [PATH] --webSiteId [WEBSITEID] -mv 1

If your downloading from "Power Pages Management" then

pac paportal download --path [PATH] --webSiteId [WEBSITEID] -mv 2

Make sure you connected to the right environment while downloading and uploading.

**Comment by Aryansharmamic** [comment]
> pac paportal download --path [PATH] --webSiteId [WEBSITEID] -mv 1

Thanks mv 2 worked for me, but i'm still confused how do i know if I'm downloading from portal management or power pages management?

because 
1) pac auth create --name [name] --url [environment url]
i connected to environment using

2) pac auth list 
Then to get my ev

3) pac auth select --index 1 
to select my ev

4) pac paportal list
to get my all sites id

5) pac paportal download --path [path] --webSiteId [website id]
download site data

**Comment by aka963** [comment]
In the home of https://make.powerpages.microsoft.com/...

click on the ellipses(...) of the targeted sites by you. It will contain Portal Management or Power Pages Management

![image](https://github.com/microsoft/powerplatform-build-tools/assets/87184188/aed54b79-283c-47ec-858a-b43be6619af2)


![image](https://github.com/microsoft/powerplatform-build-tools/assets/87184188/d301c6bf-d370-4eb9-b366-8155b472a0a9)
