### ISSUE TITLE
PP Checker 2.0.49 uses wrong resource principal (in GCC) when configured to save files. 

### ISSUE THREAD

**Issue by ToddShelton** [microsoft/powerplatform-build-tools#691]
Environment: GCC.  
Setting SaveResults: true seems to break the task by causing the checker service endpoint to default to https://gov.api.advisor.powerapps.com/ (note incorrect url for gcc), even when CustomPACheckerEndpoint: 'https://gov.api.advisor.powerapps.us/ should override it.  After unsetting SaveResults from the task interface (deletes the YAML entry) the task runs correctly.  

I have not tested this outside GCC.  

REPRO: 
1. Configure an application registration in AAD per [.](https://learn.microsoft.com/en-us/powershell/powerapps/get-started-powerapps-checker?view=pa-ps-latest#power-apps-checker-authentication-and-authorization) 
2. Create a service connection using the app reg from step 1.  
3. Configure a pipeline in GCC.  
4. Add necessary initializations.  
5. Export a suitable solution to a (pipeline) local location.  
6. Add the PP Checker 2.0.49 task, configure it to use the service connection from step 2, the local location, and set SaveResult to checked (true in YAML).    
7. Run the pipeline.  
8. Observe Error: AADSTS500011: The resource principal named https://gov.api.advisor.powerapps.com/ was not found in the tenant...
9.  Set SaveResult to false or unchecked and rerun the pipeline.   
10. Observe correct behavior.

**Comment by tehcrashxor** [comment]
Confirmed that PAC has a wrong URL mapping to https://gov.api.advisor.powerapps.com/
Tracking internally as Bug AB#3812104

---

@ToddShelton, I expect that your successful run when SaveResult is false may actually be hitting the default _public_ advisor URL.  Please check your pipeline log for one of those successful runs;  there should be a line `Endpoint: [CheckerEndpoint]` right above a line with `Checking these solution files:`

--- 

These ADO Tasks were designed for the old UI version of pipelines, so their behavior is not always obvious when in YAML.
The `CustomPACheckerEndpoint` value is only used when the task also contains a `UseDefaultPACheckerEndpoint: false`, as that second argument's default value is `true` if omitted.  (Definition of these in this [checker-v2/task.json](https://github.com/microsoft/powerplatform-build-tools/blob/d13dd3b97e849440247fe95234ca62cbab7be2d5/src/tasks/checker/checker-v2/task.json#L61C7-L65C28) file).

Unless you are also sending `UseDefaultPACheckerEndpoint`, the underlying PAC CLI will try to figure out which endpoint to hit, and the SaveResult will also send along context of the CRM Org URL inside the ServiceConnection.  The bug mentioned above is from mapping that value (*.crm9.dynamics.com) to that incorrect endpoint.  
When SaveResult is false, that extra context is not sent to PAC, so it (I expect) is hitting the default public endpoint.

Adding that `UseDefaultPACheckerEndpoint: false` to your YAML should work around the bug until we can get that fixed.

---

In the UI this task was designed for, this "Use default Power Apps Checker endpoint" box is checked by default and is the argument `UseDefaultPACheckerEndpoint` mentioned above
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/b18d70d0-7bd5-477f-8f34-70910ae400c9)

unchecking that box enables the Custom URL input
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/a0d66090-4b70-41cc-838b-e2234732ea28)

We should consider updating this task (or rather the underlying library) to not care about that switch, and just use the existence or not of the CustomPACheckerEndpoint to determine behavior.

**Comment by craig-lund-palm** [comment]
Before Version: 2.0.51 I was able to work around the "Use default Power Apps Checker endpoint" not working in a GCC tenant by just using "https://unitedstates.api.advisor.powerapps.com". 

Since the update that work around is no longer working. It seems like it is ignoring the custom URL. 

I have compared log files (in Azure DevOps) before and after the update. I see a few differences. 

`==============================================================================
Task         : Power Platform Checker
Description  : Analyze solutions using Power Apps Checker endpoint
Version      : 2.0.49
Author       : Microsoft
Help         : https://aka.ms/buildtoolsdoc Ideas, feedback: https://github.com/microsoft/powerplatform-build-tools/discussions
==============================================================================
[ 'authN to admin API: authType=UserPass; cloudInstance: UsGov' ]



[
  "'***' authenticated successfully."
]
[ 'Validating connection...' ]


[ 'Authentication profile created' ]
[
  '    * ADMIN                                    https://gov.service.powerapps.us/        : *** UsGov'
]
[ '' ]
[ 'Microsoft PowerPlatform CLI' ]
[ 'Version: 1.29.11+g9e2b163' ]
[ 'Online documentation: https://aka.ms/PowerPlatformCLI' ]
[
  'Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions'
]
[ '' ]
[
  'Warning: Argument --kind is deprecated and will be removed in a future release.'
]
[ '' ]
[
  "The Authentication Result:[***]
]
[
  'Calling pac cli inputs: solution check --path D:\\a\\1\\a\\solutions\\[***]_managed.zip --ruleSet 0ad12346-e108-40b8-a956-9a8f95ea18c9 --customEndpoint https://unitedstates.api.advisor.powerapps.com --outputDirectory D:\\a\\1\\a\\PowerAppsChecker\\checker-output --saveResults false'
]

[ '' ]
[ 'Endpoint: https://unitedstates.api.advisor.powerapps.com/' ]
[ '' ]
[ 'Checking these solution files:' ]
[ '' ]
[ '- D:\\a\\1\\a\\solutions\\[***]_managed.zip' ]`

`==============================================================================
Task         : Power Platform Checker
Description  : Analyze solutions using Power Apps Checker endpoint
Version      : 2.0.49
Author       : Microsoft
Help         : https://aka.ms/buildtoolsdoc Ideas, feedback: https://github.com/microsoft/powerplatform-build-tools/discussions
==============================================================================
[ 'authN to admin API: authType=UserPass; cloudInstance: UsGov' ]



[
  "'***' authenticated successfully."
]
[ 'Validating connection...' ]


[ 'Authentication profile created' ]
[
  '    * ADMIN                                    https://gov.service.powerapps.us/        : *** UsGov'
]
[ '' ]
[ 'Microsoft PowerPlatform CLI' ]
[ 'Version: 1.29.11+g9e2b163' ]
[ 'Online documentation: https://aka.ms/PowerPlatformCLI' ]
[
  'Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions'
]
[ '' ]
[
  'Warning: Argument --kind is deprecated and will be removed in a future release.'
]
[ '' ]
[
  "The Authentication Result:[***]
]
[
  'Calling pac cli inputs: solution check --path D:\\a\\1\\a\\solutions\\[***]_managed.zip --ruleSet 0ad12346-e108-40b8-a956-9a8f95ea18c9 --customEndpoint https://unitedstates.api.advisor.powerapps.com --outputDirectory D:\\a\\1\\a\\PowerAppsChecker\\checker-output --saveResults false'
]

[ '' ]
[ 'Endpoint: https://unitedstates.api.advisor.powerapps.com/' ]
[ '' ]
[ 'Checking these solution files:' ]
[ '' ]
[ '- D:\\a\\1\\a\\solutions\\[***]_managed.zip' ]`

The error is this. 
`[ 'Microsoft PowerPlatform CLI' ]
[ 'Version: 1.30.5+g0bf9504' ]
[ 'Online documentation: https://aka.ms/PowerPlatformCLI' ]
[
  'Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions'
]
[ '' ]
[
  'Error: AADSTS500011: The resource principal named https://gov.api.advisor.powerapps.com/ was not found in the tenant named [***]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 6191cf81-4710-4e6d-b657-acb069218200 Correlation ID: bcd26a3a-268d-4d57-8c2a-6984393fd8ff Timestamp: 2024-02-08 17:35:29Z'
]
[ '' ]`

This error, above, was getting before I added the work around. Now since the PAC CLI and Azure DevOps update it no longer works. 

I have added gov.api.advisor.powerapps.us into the custom URL and fails with the same error.

**Comment by Yocomd** [comment]
We are also experiencing this issue.  We already do have UseDefaultPACheckerEndpoint: false (and CustomPACheckerEndpoint: 'https://gov.api.advisor.powerapps.us/') in the YAML, so looks like there is no workaround for us?

**Comment by tehcrashxor** [comment]
Mapping was corrected in PAC v1.30.7, and in the just-released [PPBT v2.0.52](https://github.com/microsoft/powerplatform-build-tools/releases/tag/v2.0.52)
