### ISSUE TITLE
AuthProfileSpnSecretNotFoundWithLinuxFallback with 1.30.3 (linux-x64)

### ISSUE THREAD

**Issue by dev32** [microsoft/powerplatform-build-tools#728]
Hi,

Encountering an error with Microsoft.PowerApps.CLI.Core.linux-x64 version 1.30.3, but not with version 1.29.11.  The Service Principal configuration is the same for both as well as the `pac auth create ...` call. I couldn't find a verbose flag or a way to collect more detailed traces. Let me know if more data is needed and how it can be collected.

Working 1.29.11
```
usr@8e83700e8015:/# pac
Microsoft PowerPlatform CLI
Version: 1.29.11+g9e2b163
...

usr@8e83700e8015:/# pac auth create --name test --applicationId 9b000000-0000-0000-0000-000000000000 --clientSecret XXXXX --tenant 2e000000-0000-0000-0000-000000000000
Linux libsecret keyring is not available.  Use the '--accept-cleartext-caching' switch to permit storing in cleartext.
'9b000000-0000-0000-0000-000000000000' authenticated successfully.
Validating connection...
Authentication profile created
    * UNIVERSAL test                                                                    : 9b000000-0000-0000-0000-000000000000     Public

usr@8e83700e8015:/# pac org list
Active Display Name Environment ID                       Environment URL                         Unique Name
       test         c1000000-0000-0000-0000-000000000000 https://orgXXXX.crm.dynamics.com/ unqXXXX

usr@8e83700e8015:/# pac org select --environment c1000000-0000-0000-0000-000000000000
Looking for environment 'c1000000-0000-0000-0000-000000000000'
Selected org 'test' 'https://orgXXXX.crm.dynamics.com/' for current authentication profile.
```

Not working 1.30.3
```
usr@63fdebd55db1:/# pac
Microsoft PowerPlatform CLI
Version: 1.30.3+g0f0e0b9

usr@63fdebd55db1:/# pac auth create --name test --applicationId 9b000000-0000-0000-0000-000000000000 --clientSecret XXXXX --tenant 2e000000-0000-0000-0000-000000000000
Linux libsecret keyring is not available.  Use the '--accept-cleartext-caching' switch to permit storing in cleartext.
'9b000000-0000-0000-0000-000000000000' authenticated successfully.
Authentication profile created
    * UNIVERSAL test                           : 9b000000-0000-0000-0000-000000000000     Public

usr@63fdebd55db1:/# pac org list
Connected as 9b000000-0000-0000-0000-000000000000
Active Display Name Environment ID                       Environment URL                         Unique Name
       test         c1000000-0000-0000-0000-000000000000 https://orgXXXX.crm.dynamics.com/ unqXXXX

usr@63fdebd55db1:/# pac org select --environment c1000000-0000-0000-0000-000000000000
Connected as 9b000000-0000-0000-0000-000000000000
Looking for environment 'c1000000-0000-0000-0000-000000000000'
Validating connection...
Connected to...
Could not connect to the Dataverse organization at https://orgXXXX.crm.dynamics.com/.
Microsoft PowerPlatform CLI
Version: 1.30.3+g0f0e0b9
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Failed to connect to Dataverse
    ExternalTokenManagement Authentication Requested but not configured correctly. 003
        AuthProfileSpnSecretNotFoundWithLinuxFallback
```

Thanks!

**Comment by tehcrashxor** [comment]
In 1.29.11 and before, `pac org select` would update the AuthProfile to retarget it to the selected organization, but was not validating if the user could actually communicate with that environment.  In your 1.29.11 case, if you were to run `pac solution list`,  `pac org who`, or any other organization-aware verb, you would see a similar failure.

1.30.3 validates that the `pac org select` target is connectable, but the error message in this case is not particularly helpful.  (Tracking work for a better error message internally by [AB#3798907](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/3798907).)

---

The reason for the failure:

Unlike regular users, SPNs (Service Principals) do not receive RefreshTokens from Entra ID / AAD when authenticating, and must use their ClientSecret every time they need to either Refresh their access token (which typically expires after 1 hour, but is configurable) or need to acquire a token for a different resource.  PAC needs to store that value in order to perform those operations, which is done differently on each platform.

- Windows encrypts the value with the Windows Data Protection API
- macOS encrypts and stores the value with Keychain
- Linux 
  - if LibSecret is installed, if a Secret Service such as Gnome KeyRing is running, if D-Bus is running, then the secret is encrypted and stored within that KeyRing
  - else, we can only store the value in plaintext (chmod to only that user).  As this could be a very bad idea on shared machines, the user must make the decision to accept that risk and use the `--accept-cleartext-caching` switch when creating the auth profile with `pac auth create`

The output to your `pac auth create` calls detected that Linux KeyRing was not available for secure storage, hence the included `--accept-cleartext-caching` message.

**Comment by tiagodenoronha** [comment]
Hey, so I got the exact same error, albeit in a different step.

This is my current pipeline:


```
trigger: none

parameters:
  - name: ServiceConnection
    type: string
    default: "Dev SC"
    displayName: "Service Connection Name"

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerPlatformToolInstaller@2
  displayName: 'Install Power Platform CLI'
  inputs:
    addToolsToPath: true

- task: PowerPlatformSetConnectionVariables@2
  displayName: 'Set Power Platform Connection Variables'
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: ${{ parameters.ServiceConnection }}

- pwsh: |
    pac auth create `
      --applicationId "$(PowerPlatformSetConnectionVariables.BuildTools.ApplicationId)" `
      --clientSecret "$(PowerPlatformSetConnectionVariables.BuildTools.ClientSecret)" `
      --tenant "$(PowerPlatformSetConnectionVariables.BuildTools.TenantId)" `
      --environment "$(BuildTools.EnvironmentUrl)"
  displayName: 'Create Pac Auth'

# This works on windows, but fails on linux. Not 100% sure why.
# This link has more information for the same error, but not the same step
# https://github.com/microsoft/powerplatform-build-tools/issues/728
- pwsh: |
    pac connection create `
      --application-id "$(PowerPlatformSetConnectionVariables.BuildTools.ApplicationId)" `
      --client-secret "$(PowerPlatformSetConnectionVariables.BuildTools.ClientSecret)" `
      --tenant-id "$(PowerPlatformSetConnectionVariables.BuildTools.TenantId)" `
      --name "${{ parameters.ServiceConnection }}_dataverseconn" `
      --environment "$(BuildTools.EnvironmentUrl)"
  displayName: 'Create Dataverse Connection'

```

I got it working by using the windows-latest, however I would like to run everything in the ubuntu-latest pool.
The applicationid and clientsecret are already stored as secrets, shouldn't that be enough for the ubuntu agent?
