### ISSUE TITLE
Unable to backup environment or "Get-AdminPowerAppEnvironment" with App Registration

### ISSUE THREAD

**Issue by craig-lund-palm** [microsoft/powerplatform-build-tools#892]
Recently had errors when using Azure DevOps build tools "Backup Environment" and PowerShell "Get-AdminPowerAppEnvironment". 

Backup Environment indicates: "Error: The service principal with id '***' for application *** does not have permission to access the path '[https://10.0.1.23:23477/providers/Microsoft.BusinessAppPlatform/environments/***/backups?api-version=2020-08-01'](https://10.0.1.23:23477/providers/Microsoft.BusinessAppPlatform/environments/***/backups?api-version=2020-08-01%27) in tenant ***."

PowerShell: No environments found with "Get-AdminPowerAppEnvironment -Filter *$DomainName*"

This is a GCC environment with endpoint of "usgov". 

``` 
      - task: PowerPlatformBackupEnvironment@2
        name: backupenvironment
        displayName: Backup Environment...
        inputs:
          authenticationType: 'PowerPlatformSPN'
          PowerPlatformSPN: 'https://${{parameters.DomainName}}.$(DomainSuffix)/'
          Environment: 'https://${{parameters.DomainName}}.$(DomainSuffix)/'
          BackupLabel: 'Full Backup - $(Build.BuildNumber) ${{parameters.SolutionName}}'
        enabled: true
```

**Comment by tehcrashxor** [comment]
For an App / Service Principal to talk to the Admin endpoints, it needs to be registered with the BAP Admin API.

The simplest way to do this is with the PAC CLI via `pac admin application register --application-id [AppID]`, which will need to be run by another user that has the proper permissions.

(The documentation on this, [Registering an admin management application](https://learn.microsoft.com/en-us/power-platform/admin/powerplatform-api-create-service-principal#registering-an-admin-management-application), needs to updated to reflect that the PAC Command works for this.)

**Comment by shanaythakkar** [comment]
Echoing the same issues as mentioned above. Even after registration I am unable to see any environments with the command. Am wondering if I'm missing a step somewhere.

**Comment by craig-lund-palm** [comment]
I have removed all management apps. When I run 

`pac admin application list` I get;

```
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 37d5930d-999e-4067-af62-3642c34b4957, Exception Type: System.InvalidOperationException...
```

When I run `Get-PowerAppManagementApps` I get;

```
value
-----
{}
```

I have a Power Platform Administrator role assignment. I had a tenant Global Admin perform the following. 

`pac admin application register --application-id e2bb****-****-****-****-********28a7` with result;

```
Connected as ***@***.gov
Registering Entra ID Application 'e2bb****-****-****-****-********28a7'... Done
```

**Using an Azure DevOps Pipeline with Service connection to desired environment I run**

'WhoAmI', and get;

```
[ 'Connected as ***' ]
[ 'Connected to... ***UAT***' ]
[ 'Organization Information' ]
[
  '  Org ID:                     4bd7****-****-****-****-********f13c'
]
[ '  Unique Name:                ***' ]
[ '  Friendly Name:              ***UAT***' ]
[
  '  Org URL:                    https://***uat.crm9.dynamics.com/'
]
[
  '  User Email:                 ***'
]
[
  '  User ID:                    1ea0****-****-****-****-********e985'
]
[
  '  Environment ID:             b747****-****-****-****-********17a4'
]
```

'Backup Environment', and get;

```
[
  "Error: The service principal with id 'c00e****-****-****-****-********48ca' for application *** does not have permission to access the path '[https://10.0.1.28:20019/providers/Microsoft.BusinessAppPlatform/environments/b747****-****-****-****-********17a4/backups?api-version=2020-08-01'](https://10.0.1.28:20019/providers/Microsoft.BusinessAppPlatform/environments/b747****-****-****-****-********17a4/backups?api-version=2020-08-01%27) in tenant 561b****-****-****-****-********85af."
]
```

The Global Admin and I searched all over and could not find any reference to the service principal with id `'c00e****-****-****-****-********48ca'` in the tenant.

Please advise! If I should create a support ticket.

**Comment by tehcrashxor** [comment]
@craig-lund-palm 
GCC Moderate is a little odd as tenants there can have resources in both the Public and GCC clouds, so my next guess is that you might be doing is running `pac admin application register` against Public then trying to use Backup Environment in GCC, or vice versa.
When you ran `pac admin application register`, what was the Cloud setting on the auth profile you ran that command with?  (`pac auth list` has a column that has that information.  `pac auth create` has a `--cloud` parameter which can be used to explicitly set it to `UsGov`, though passing in a `crm9.dynamics.com` URL to the `--environment` parameter will also infer that)

For the SPN used within the ADO task -- is the "Server URL" field on the SPN's Service Connection set to a `crm9` URL?

------

> The Global Admin and I searched all over and could not find any reference to the service principal with id [...]

Apps and Service Principals are _technically_ two distinct entities, even though they not treated as separate most of the time.  
That "Service Principal ID" returned in the error from the BAP API is the App's Service Principal's Object ID.  It is not visible in the Azure Portal IIRC.  You can only really see that by cracking open the JWT auth tokens, or by making API calls to [Microsoft Graph's servicePrincipal endpoint(s)](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-1.0&tabs=http).  

Nothing in PAC or the Power Platform Build Tools cares about that ID, as we use the App ID everywhere, so that value can just be ignored.

-------

> Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 37d5930d-999e-4067-af62-3642c34b4957, Exception Type: System.InvalidOperationException...

Looked up the Exception in our telemetry, and looks like this is a bug on PAC's output.  The command returned an empty list, and the output code to transform that list into a text grid wasn't expecting it to be empty.   

Wrote up a bug to track that issue.

**Comment by craig-lund-palm** [comment]
@tehcrashxor 
Interesting call out on the explicit auth create with `--cloud` set to `UsGov`. I do not recall using that as I just let the authentication dialog open and authenticate there. I removed the management app and recreated my auth with cloud and re-registered the management app and now it works. I made an assumption that when I run using .gov credentials it would just know. Thanks for clarifying that I won't make that oversight again. 

SPN Service Connections all do use the `crm9` url. I do see the --environment passes the `crm9` url.

**Comment by tehcrashxor** [comment]
@shanaythakkar , are you also trying this against a GCC resource as craig was?
Does running `pac admin application register` resolve your issue as well?

**Comment by craig-lund-palm** [comment]
@tehcrashxor
Thanks for all your help! 

For anyone who finds this, using the pac CLI , PowerShell, or API the key to this resolution is setting the "Cloud" or whatever reference to "UsGov". Depending on what tenant you are accessing this may change but understanding how critical that is the key. Thank you to @tehcrashxor for helping me understand the undocumented importance.

**Comment by shanaythakkar** [comment]
Hey!

Yup this solved my problem. Thanks for the insight!

Regards,

Shanay Thakkar

**Comment by tehcrashxor** [comment]
Great to hear.  Let us know if you run into anything else here.
